Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false

  # K3s Master
  config.vm.define "k3s-master" do |master|
    master.vm.hostname = "k3s-master"
    master.vm.network "private_network", ip: "10.0.0.10"
    
    master.vm.provider "virtualbox" do |vb|
      vb.name = "k3s-master"
      vb.memory = 2048
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--groups", "/DevOpsLab"]
    end
    
    master.vm.provision "shell", inline: <<-SHELL
      # Install K3s master
      curl -sfL https://get.k3s.io | sh -
      
      # Setup kubectl for vagrant user
      mkdir -p /home/vagrant/.kube
      cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      chown vagrant:vagrant /home/vagrant/.kube/config
      
      # Get node token for workers
      cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
    SHELL
  end

  # K3s Workers
  (1..2).each do |i|
    config.vm.define "k3s-worker-#{i}" do |worker|
      worker.vm.hostname = "k3s-worker-#{i}"
      worker.vm.network "private_network", ip: "10.0.0.#{10 + i}"
      
      worker.vm.provider "virtualbox" do |vb|
        vb.name = "k3s-worker-#{i}"
        vb.memory = 1024
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--groups", "/DevOpsLab"]
      end
      
      worker.vm.provision "shell", inline: <<-SHELL
        # Wait for master to be ready
        sleep 30
        
        # Join K3s cluster
        curl -sfL https://get.k3s.io | K3S_URL=https://10.0.0.10:6443 K3S_TOKEN=$(cat /vagrant/node-token) sh -
      SHELL
    end
  end
end