# -*- mode: ruby -*-
# vi: set ft=ruby :

# To start, run: vagrant up > vagrant_up.log 2>&1

machines = {
  "srv-vm-cn01" => { "memory" => "512",  "cpu" => "2", "ip" => "2" }
}

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false

  # Disable default /vagrant sync
  config.vm.synced_folder ".", "/vagrant", disabled: true

  machines.each do |name, conf|
    config.vm.define name do |machine|
      machine.vm.hostname = name

      # Network configuration
      machine.vm.network "private_network", ip: "10.0.0.#{conf["ip"]}"

      # Provisioning scripts
      machine.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"
      machine.vm.provision "shell", path: "scripts/bootstrap.sh"
      machine.vm.provision "shell", path: "scripts/create_user_ies.sh"
      machine.vm.provision "shell", path: "scripts/configure_network.sh"
      machine.vm.provision "shell", path: "scripts/configure_ssh.sh"
      machine.vm.provision "shell", path: "scripts/verify.sh"
      machine.vm.provision "shell", path: "scripts/provision.sh"

      # VirtualBox settings
      machine.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.memory = conf["memory"].to_i
        vb.cpus = conf["cpu"].to_i
        vb.customize ["modifyvm", :id, "--groups", "/DevOpsLab"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--vram", "16"]
      end
    end
  end
end

