---
- name: Configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    mysql_root_password: "p2ssw0rd"
    mysql_databases:
      - name: notes
        encoding: utf8mb4
        collation: utf8mb4_unicode_ci
    mysql_users:
      - name: notesapp
        host: "%"
        password: "p2ssw0rd"
        priv: "notes.*:ALL"
        append_privs: yes
    mysql_packages:
      - mysql-server
      - python3-mysqldb
    mysql_service: mysql
    mysql_port: 3306
    mysql_bind_address: "0.0.0.0"

  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql