Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  
  # Swarm Manager
  config.vm.define "swarm-manager" do |manager|
    manager.vm.hostname = "swarm-manager"
    manager.vm.network "private_network", ip: "10.0.0.50"
    manager.vm.network "forwarded_port", guest: 80, host: 8090, hostip: "127.0.0.1"
    
    manager.vm.provider "virtualbox" do |vb|
      vb.name = "swarm-manager"
      vb.memory = 1024
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--groups", "/DevOpsLab"]
    end
    
    manager.vm.provision "shell", path: "provision.sh"
  end

  # Swarm Workers
  (1..2).each do |i|
    config.vm.define "swarm-worker-#{i}" do |worker|
      worker.vm.hostname = "swarm-worker-#{i}"
      worker.vm.network "private_network", ip: "10.0.0.#{50 + i}"
      
      worker.vm.provider "virtualbox" do |vb|
        vb.name = "swarm-worker-#{i}"
        vb.memory = 1024
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--groups", "/DevOpsLab"]
      end
      
      worker.vm.provision "shell", path: "provision.sh"
    end
  end
end