---
- name: Install K3s Master Node
  hosts: master
  become: true
  vars:
    k3s_version: "v1.28.5+k3s1"

  tasks:
    - name: Install K3s on master node
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -s - server \
          --cluster-init \
          --write-kubeconfig-mode 644 \
          --disable traefik \
          --node-external-ip {{ ansible_default_ipv4.address }}
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s to be ready
      wait_for:
        port: 6443
        host: "{{ ansible_default_ipv4.address }}"
        delay: 30
        timeout: 300

    - name: Get K3s token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Set facts for workers
      set_fact:
        k3s_master_ip: "{{ ansible_default_ipv4.address }}"
        k3s_token: "{{ k3s_token.content | b64decode | trim }}"

- name: Install K3s Worker Nodes
  hosts: workers
  become: true
  vars:
    k3s_version: "v1.28.5+k3s1"

  tasks:
    - name: Install K3s on worker nodes
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_URL=https://{{ hostvars[groups['master'][0]]['k3s_master_ip'] }}:6443 K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_token'] }} sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for worker to join
      wait_for:
        timeout: 60

- name: Configure kubectl access
  hosts: master
  become: true
  tasks:
    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy kubeconfig for ubuntu user
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        remote_src: true
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Update kubeconfig server address
      replace:
        path: /home/ubuntu/.kube/config
        regexp: 'https://127.0.0.1:6443'
        replace: 'https://{{ ansible_default_ipv4.address }}:6443'

    - name: Install NGINX Ingress Controller
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml
      become_user: ubuntu

    - name: Show cluster status
      shell: kubectl get nodes -o wide
      become_user: ubuntu
      register: cluster_status

    - name: Display cluster info
      debug:
        msg: |
          K3s Cluster Ready!
          Master IP: {{ ansible_default_ipv4.address }}

          Cluster Status:
          {{ cluster_status.stdout }}

          Access: ssh ubuntu@{{ ansible_default_ipv4.address }}
          Then: kubectl get nodes