Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.hostname = "monitoring"
    monitoring.vm.network "private_network", ip: "10.0.0.30"
    monitoring.vm.network "forwarded_port", guest: 3000, host: 3000, hostip: "127.0.0.1"
    monitoring.vm.network "forwarded_port", guest: 9090, host: 9090, hostip: "127.0.0.1"
    
    monitoring.vm.provider "virtualbox" do |vb|
      vb.name = "monitoring"
      vb.memory = 2048
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--groups", "/DevOpsLab"]
    end
    
    monitoring.vm.provision "shell", path: "provision.sh"
  end
end