Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "10.0.0.20"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080, hostip: "127.0.0.1"
    
    jenkins.vm.provider "virtualbox" do |vb|
      vb.name = "jenkins"
      vb.memory = 2048
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--groups", "/DevOpsLab"]
    end
    
    jenkins.vm.provision "shell", path: "provision.sh"
  end
end