---
# K3s Cluster Setup Role
- name: Install K3s on master
  shell: curl -sfL https://get.k3s.io | sh -
  when: inventory_hostname in groups['master']

- name: Get K3s token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  when: inventory_hostname in groups['master']

- name: Join workers to cluster
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['master'][0]]['ansible_default_ipv4']['address'] }}:6443 \
    K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_token']['content'] | b64decode | trim }} sh -
  when: inventory_hostname in groups['workers']

- name: Setup kubectl for ubuntu user
  block:
    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
    
    - name: Copy kubeconfig
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0600'
        remote_src: yes
  when: inventory_hostname in groups['master']